# Generated by Django 3.2 on 2021-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prize', models.FloatField(max_length=10)),
                ('stock', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
